// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtf3_10egwtoCwBX1rq5Ij-EG3cK5pU5A',
    appId: '1:478903510182:web:0bc84c8b102119ccca0067',
    messagingSenderId: '478903510182',
    projectId: 'simi-rq',
    authDomain: 'simi-rq.firebaseapp.com',
    storageBucket: 'simi-rq.firebasestorage.app',
    measurementId: 'G-36FJ6TZB8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFfia0xofewydHTTvnwOv6MeG27sFY9I',
    appId: '1:478903510182:android:60423a36e60dd2c7ca0067',
    messagingSenderId: '478903510182',
    projectId: 'simi-rq',
    storageBucket: 'simi-rq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVok7kzUaSkTZvqESfhEsnXx0-WL85flM',
    appId: '1:478903510182:ios:1543c13b0ec56f4aca0067',
    messagingSenderId: '478903510182',
    projectId: 'simi-rq',
    storageBucket: 'simi-rq.firebasestorage.app',
    iosClientId: '478903510182-isita4ldoe329egjiss8ufl4uc4lrv3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.miSchoolproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVok7kzUaSkTZvqESfhEsnXx0-WL85flM',
    appId: '1:478903510182:ios:1543c13b0ec56f4aca0067',
    messagingSenderId: '478903510182',
    projectId: 'simi-rq',
    storageBucket: 'simi-rq.firebasestorage.app',
    iosClientId: '478903510182-isita4ldoe329egjiss8ufl4uc4lrv3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.miSchoolproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtf3_10egwtoCwBX1rq5Ij-EG3cK5pU5A',
    appId: '1:478903510182:web:a60072c011a0c262ca0067',
    messagingSenderId: '478903510182',
    projectId: 'simi-rq',
    authDomain: 'simi-rq.firebaseapp.com',
    storageBucket: 'simi-rq.firebasestorage.app',
    measurementId: 'G-B066NKLLXC',
  );
}
